# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/hi6210sft/setup-makefiles.sh

PRODUCT_COPY_FILES += \
vendor/huawei/hi6210sft/proprietary/bin/atcmdserver:system/bin/atcmdserver \
vendor/huawei/hi6210sft/proprietary/ons.bin:system/ons.bin \
vendor/huawei/hi6210sft/proprietary/isp.bin:system/isp.bin \
vendor/huawei/hi6210sft/proprietary/phone.prop:system/phone.prop \
vendor/huawei/hi6210sft/proprietary/bin/mediaserver:system/bin/mediaserver \
vendor/huawei/hi6210sft/proprietary/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudiopolicyservice.so:system/lib/libaudiopolicyservice.so \
vendor/huawei/hi6210sft/proprietary/lib64/libaudiopolicyservice.so:system/lib64/libaudiopolicyservice.so \
vendor/huawei/hi6210sft/proprietary/lib/libsrsprocessing.so:system/lib/libsrsprocessing.so \
vendor/huawei/hi6210sft/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
vendor/huawei/hi6210sft/proprietary/lib64/libcameraservice.so:system/lib64/libcameraservice.so \
vendor/huawei/hi6210sft/proprietary/lib/drm/libdrmhwomavoneplugin.so:system/lib/drm/libdrmhwomavoneplugin.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so.so\
vendor/huawei/hi6210sft/proprietary/bin/glgps:system/bin/glgps\
vendor/huawei/hi6210sft/proprietary/bin/device_monitor:system/bin/device_monitor\
vendor/huawei/hi6210sft/proprietary/bin/gpsdaemon:system/bin/gpsdaemon\
vendor/huawei/hi6210sft/proprietary/bin/gpslogd:system/bin/gpslogd\
vendor/huawei/hi6210sft/proprietary/bin/hdb:system/bin/hdb\
vendor/huawei/hi6210sft/proprietary/bin/hwnff:system/bin/hwnff\
vendor/huawei/hi6210sft/proprietary/bin/hwnffserver:system/bin/hwnffserver\
vendor/huawei/hi6210sft/proprietary/bin/hwpged:system/bin/hwpged\
vendor/huawei/hi6210sft/proprietary/bin/hw_ueventd:system/bin/hw_ueventd\
vendor/huawei/hi6210sft/proprietary/bin/mac_addr_normalization:system/bin/mac_addr_normalization\
vendor/huawei/hi6210sft/proprietary/bin/rild:system/bin/rild\
vendor/huawei/hi6210sft/proprietary/lib64/egl/libGLES_mali.so:system/lib64/egl/libGLES_mali.so\
vendor/huawei/hi6210sft/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/audio.a2dp.default.so:system/lib64/hw/audio.a2dp.default.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/audio.primary.default.so:system/lib64/hw/audio.primary.default.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/audio.primary.hi6210sft.so:system/lib/hw/audio.primary.hi6210sft.so \
vendor/huawei/hi6210sft/proprietary/lib64/hw/audio.primary.hi6210sft.so:system/lib64/hw/audio.primary.hi6210sft.so \
vendor/huawei/hi6210sft/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/audio.r_submix.default.so:system/lib64/hw/audio.r_submix.default.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
vendor/huawei/hi6210sft/proprietary/lib64/hw/camera.hi6210sft.so:system/lib64/hw/camera.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/camera.hi6210sft.so:system/lib/hw/camera.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/bastet.hi6210sft.so:system/lib64/hw/bastet.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/keystore.hi6210sft.so:system/lib64/hw/keystore.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/keystore.hi6210sft.so:system/lib/hw/keystore.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/gps.hi6210sft.so:system/lib64/hw/gps.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/gps.hi110x.default.so:system/lib64/hw/gps.hi110x.default.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/gps.hi110x.default.so:system/lib/hw/gps.hi110x.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/libbcmfm_if.so:system/lib64/hw/libbcmfm_if.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/libbcmfm_if.so:system/lib/hw/libbcmfm_if.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/libhisifm_if.so:system/lib64/hw/libhisifm_if.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/libhisifm_if.so:system/lib/hw/libhisifm_if.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/lights.default.so:system/lib64/hw/lights.default.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/nfc_nci.pn54x.default.so:system/lib64/hw/nfc_nci.pn54x.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/power.default.so:system/lib64/hw/power.default.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/sensors.hi6210sft.so:system/lib64/hw/sensors.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/sensors.hi6210sft.so:system/lib/hw/sensors.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/gralloc.hi6210sft.so:system/lib64/hw/gralloc.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/gralloc.hi6210sft.so:system/lib/hw/gralloc.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/hwcomposer.default.so:system/lib/hw/hwcomposer.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/hwcomposer.default.so:system/lib64/hw/hwcomposer.default.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/hwcomposer.hi6210sft.so:system/lib64/hw/hwcomposer.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/hwcomposer.hi6210sft.so:system/lib/hw/hwcomposer.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib64/hw/memtrack.hi6210sft.so:system/lib64/hw/memtrack.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib/hw/memtrack.hi6210sft.so:system/lib/hw/memtrack.hi6210sft.so\
vendor/huawei/hi6210sft/proprietary/lib64/libhardware.so:system/lib64/libhardware.so\
vendor/huawei/hi6210sft/proprietary/lib/libhardware.so:system/lib/libhardware.so\
vendor/huawei/hi6210sft/proprietary/lib64/libui.so:system/lib64/libui.so\
vendor/huawei/hi6210sft/proprietary/lib/libui.so:system/lib/libui.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_hwnsd_sf.so:system/lib64/lib_hwnsd_sf.so\
vendor/huawei/hi6210sft/proprietary/lib/lib_hwnsd_sf.so:system/lib/lib_hwnsd_sf.so\
vendor/huawei/hi6210sft/proprietary/lib64/libgui.so:system/lib64/libgui.so\
vendor/huawei/hi6210sft/proprietary/lib/libgui.so:system/lib/libgui.so\
vendor/huawei/hi6210sft/proprietary/lib64/libhwaps.so:system/lib64/libhwaps.so\
vendor/huawei/hi6210sft/proprietary/lib/libhwaps.so:system/lib/libhwaps.so\
vendor/huawei/hi6210sft/proprietary/lib/libion.so:system/lib/libion.so\
vendor/huawei/hi6210sft/proprietary/lib64/libion.so:system/lib64/libion.so\
vendor/huawei/hi6210sft/proprietary/lib64/libsurfaceflinger.so:system/lib64/libsurfaceflinger.so\
vendor/huawei/hi6210sft/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so\
vendor/huawei/hi6210sft/proprietary/lib64/libhardware_legacy.so:system/lib64/libhardware_legacy.so\
vendor/huawei/hi6210sft/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so\
vendor/huawei/hi6210sft/proprietary/lib64/libCameraHwCallBack.so:system/lib64/libCameraHwCallBack.so\
vendor/huawei/hi6210sft/proprietary/lib/libCameraHwCallBack.so:system/lib/libCameraHwCallBack.so\
vendor/huawei/hi6210sft/proprietary/lib64/libaudioom.so:system/lib64/libaudioom.so\
vendor/huawei/hi6210sft/proprietary/lib/libaudioom.so:system/lib/libaudioom.so\
vendor/huawei/hi6210sft/proprietary/lib64/libbalong-ril.so:system/lib64/libbalong-ril.so\
vendor/huawei/hi6210sft/proprietary/lib64/libril.so:system/lib64/libril.so\
vendor/huawei/hi6210sft/proprietary/lib/libril.so:system/lib/libril.so\
vendor/huawei/hi6210sft/proprietary/lib64/libbalong-ril-1.so:system/lib64/libbalong-ril-1.so\
vendor/huawei/hi6210sft/proprietary/lib64/libbalong_audio_ril.so:system/lib64/libbalong_audio_ril.so\
vendor/huawei/hi6210sft/proprietary/lib/libbalong_audio_ril.so:system/lib/libbalong_audio_ril.so\
vendor/huawei/hi6210sft/proprietary/lib64/libcamera_client.so:system/lib64/libcamera_client.so\
vendor/huawei/hi6210sft/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so\
vendor/huawei/hi6210sft/proprietary/lib/libcamera_core.so:system/lib/libcamera_core.so\
vendor/huawei/hi6210sft/proprietary/lib64/libCameraHwParam.so:system/lib64/libCameraHwParam.so\
vendor/huawei/hi6210sft/proprietary/lib/libCameraHwParam.so:system/lib/libCameraHwParam.so\
vendor/huawei/hi6210sft/proprietary/lib64/libCameraHwSendCmd.so:system/lib64/libCameraHwSendCmd.so\
vendor/huawei/hi6210sft/proprietary/lib/libCameraHwSendCmd.so:system/lib/libCameraHwSendCmd.so\
vendor/huawei/hi6210sft/proprietary/lib64/libgnuexif.so:system/lib64/libgnuexif.so\
vendor/huawei/hi6210sft/proprietary/lib/libgnuexif.so:system/lib/libgnuexif.so\
vendor/huawei/hi6210sft/proprietary/lib64/libservices.huawei.so:system/lib64/libservices.huawei.so\
vendor/huawei/hi6210sft/proprietary/lib/libservices.huawei.so:system/lib/libservices.huawei.so\
vendor/huawei/hi6210sft/proprietary/lib64/libteec.so:system/lib64/libteec.so\
vendor/huawei/hi6210sft/proprietary/lib64/libbt_factory_test.so:system/lib64/libbt_factory_test.so\
vendor/huawei/hi6210sft/proprietary/lib64/libbt_factory_test_hi110x.so:system/lib64/libbt_factory_test_hi110x.so\
vendor/huawei/hi6210sft/proprietary/lib64/libconn_factory_test.so:system/lib64/libconn_factory_test.so\
vendor/huawei/hi6210sft/proprietary/lib64/libfm_hal.so:system/lib64/libfm_hal.so\
vendor/huawei/hi6210sft/proprietary/lib64/libfm_interface.so:system/lib64/libfm_interface.so\
vendor/huawei/hi6210sft/proprietary/lib64/libfm_jni.so:system/lib64/libfm_jni.so\
vendor/huawei/hi6210sft/proprietary/lib64/libfm_volume.so:system/lib64/libfm_volume.so\
vendor/huawei/hi6210sft/proprietary/lib64/libgps_factory_test.so:system/lib64/libgps_factory_test.so\
vendor/huawei/hi6210sft/proprietary/lib64/libgps_factory_test_hi110x.so:system/lib64/libgps_factory_test_hi110x.so\
vendor/huawei/hi6210sft/proprietary/lib64/libhardware_legacy_bcm.so:system/lib64/libhardware_legacy_bcm.so\
vendor/huawei/hi6210sft/proprietary/lib64/libhardware_legacy_hisi.so:system/lib64/libhardware_legacy_hisi.so\
vendor/huawei/hi6210sft/proprietary/lib64/libhuawei_mmi_test.so:system/lib64/libhuawei_mmi_test.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_ffmpeg.so:system/lib64/lib_k3_ffmpeg.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omx_avc.so:system/lib64/lib_k3_omx_avc.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omx_avcenc.so:system/lib64/lib_k3_omx_avcenc.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omxcore.so:system/lib64/lib_k3_omxcore.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omx_mpeg2.so:system/lib64/lib_k3_omx_mpeg2.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omx_mpeg4.so:system/lib64/lib_k3_omx_mpeg4.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omx_rv.so:system/lib64/lib_k3_omx_rv.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omx_vc1.so:system/lib64/lib_k3_omx_vc1.so\
vendor/huawei/hi6210sft/proprietary/lib64/lib_k3_omx_vp8.so:system/lib64/lib_k3_omx_vp8.so\
vendor/huawei/hi6210sft/proprietary/lib64/libmedia_jni.huawei.so:system/lib64/libmedia_jni.huawei.so\
vendor/huawei/hi6210sft/proprietary/lib64/libmtp.huawei.so:system/lib64/libmtp.huawei.so\
vendor/huawei/hi6210sft/proprietary/lib64/libnfc-nci.so:system/lib64/libnfc-nci.so\
vendor/huawei/hi6210sft/proprietary/lib64/libnfc_nci_jni.so:system/lib64/libnfc_nci_jni.so\
vendor/huawei/hi6210sft/proprietary/lib64/libnfc_ndef.so:system/lib64/libnfc_ndef.so\
vendor/huawei/hi6210sft/proprietary/lib64/libOpenMAXAL.so:system/lib64/libOpenMAXAL.so\
vendor/huawei/hi6210sft/proprietary/lib64/libOpenSLES.so:system/lib64/libOpenSLES.so\
vendor/huawei/hi6210sft/proprietary/lib64/libwifi_factory_test.so:system/lib64/libwifi_factory_test.so\
vendor/huawei/hi6210sft/proprietary/lib64/libwifi_factory_test_hi110x.so:system/lib64/libwifi_factory_test_hi110x.so\
vendor/huawei/hi6210sft/proprietary/lib64/libwpa_client.so:system/lib64/libwpa_client.so\
vendor/huawei/hi6210sft/proprietary/lib64/libwpa_client_hisi.so:system/lib64/libwpa_client_hisi.so\
vendor/huawei/hi6210sft/proprietary/lib/libteec.so:system/lib/libteec.so\
vendor/huawei/hi6210sft/proprietary/lib/libaudioflinger.huawei.so:system/lib/libaudioflinger.huawei.so\
vendor/huawei/hi6210sft/proprietary/lib/libhuaweiaudioalgoservice.so:system/lib/libhuaweiaudioalgoservice.so\
vendor/huawei/hi6210sft/proprietary/lib/libhuaweiprocessing.so:system/lib/libhuaweiprocessing.so\
vendor/huawei/hi6210sft/proprietary/lib/libjpu.so:system/lib/libjpu.so\
vendor/huawei/hi6210sft/proprietary/lib64/libjpu.so:system/lib64/libjpu.so\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/4343A0_001.001.034.0056.0193_ORC.hcd:system/vendor/firmware/4343A0_001.001.034.0056.0193_ORC.hcd\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/BCM4334B0_002.001.013.1554.1613_RC.hcd:system/vendor/firmware/BCM4334B0_002.001.013.1554.1613_RC.hcd\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/fw_bcm4343s_apsta_hw.bin:system/vendor/firmware/fw_bcm4343s_apsta_hw.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/fw_bcm4343s_hw.bin:system/vendor/firmware/fw_bcm4343s_hw.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/fw_bcm4343s_p2p_hw.bin:system/vendor/firmware/fw_bcm4343s_p2p_hw.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/fw_bcm4343s_test_hw_apsta.bin:system/vendor/firmware/fw_bcm4343s_test_hw_apsta.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/GNSS.bin:system/vendor/firmware/GNSS.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/nvram4343s_hw.txt:system/vendor/firmware/nvram4343s_hw.txt\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/nvram_CHERRY_PLUS_TL00.txt:system/vendor/firmware/nvram_CHERRY_PLUS_TL00.txt\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/nvram_CHERRY_PLUS_TL20M.txt:system/vendor/firmware/nvram_CHERRY_PLUS_TL20M.txt\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/nvram_CHERRY_PLUS_UL00.txt:system/vendor/firmware/nvram_CHERRY_PLUS_UL00.txt\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/sdio_cfg:system/vendor/firmware/sdio_cfg\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/SDIO_CMP.bin:system/vendor/firmware/SDIO_CMP.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/SDIO_COD.bin:system/vendor/firmware/SDIO_COD.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/SDIO_RW.bin:system/vendor/firmware/SDIO_RW.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/SDIO_RW_ALICE_TL00_FEM.bin:system/vendor/firmware/SDIO_RW_ALICE_TL00_FEM.bin\
vendor/huawei/hi6210sft/proprietary/vendor/firmware/SDIO_RW_ALICE_TL02_FEM.bin:system/vendor/firmware/SDIO_RW_ALICE_TL02_FEM.bin\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libbt-vendor-hi110x.so:system/vendor/lib/libbt-vendor-hi110x.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libee_core.so:system/vendor/lib/libee_core.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libee_support.so:system/vendor/lib/libee_support.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libexticonv.so:system/vendor/lib/libexticonv.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libposclientcore.so:system/vendor/lib/libposclientcore.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libslpgw-single.so:system/vendor/lib/libslpgw-single.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libstlport_shared_rtti.so:system/vendor/lib/libstlport_shared_rtti.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libsupl.so:system/vendor/lib/libsupl.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so\
vendor/huawei/hi6210sft/proprietary/vendor/lib64/libbt-vendor-hi110x.so:system/vendor/lib64/libbt-vendor-hi110x.so\
vendor/huawei/hi6210sft/proprietary/vendor/framework/com.huawei.audioalgo.jar:system/vendor/framework/com.huawei.audioalgo.jar\
vendor/huawei/hi6210sft/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
vendor/huawei/hi6210sft/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd \
vendor/huawei/hi6210sft/proprietary/bin/afar:system/bin/afar \
vendor/huawei/hi6210sft/proprietary/bin/agnsscontrol:system/bin/agnsscontrol \
vendor/huawei/hi6210sft/proprietary/bin/agnsslog:system/bin/agnsslog \
vendor/huawei/hi6210sft/proprietary/bin/akmd09911:system/bin/akmd09911 \
vendor/huawei/hi6210sft/proprietary/bin/bastetd:system/bin/bastetd \
vendor/huawei/hi6210sft/proprietary/bin/chargelogcat:system/bin/chargelogcat \
vendor/huawei/hi6210sft/proprietary/bin/checkntfs:system/bin/checkntfs \
vendor/huawei/hi6210sft/proprietary/bin/chr_logd:system/bin/chr_logd \
vendor/huawei/hi6210sft/proprietary/bin/crashnotice:system/bin/crashnotice \
vendor/huawei/hi6210sft/proprietary/bin/data_cleaner:system/bin/data_cleaner \
vendor/huawei/hi6210sft/proprietary/bin/dexopt-wrapper:system/bin/dexopt-wrapper \
vendor/huawei/hi6210sft/proprietary/bin/diagserver:system/bin/diagserver \
vendor/huawei/hi6210sft/proprietary/bin/dmesgcat:system/bin/dmesgcat \
vendor/huawei/hi6210sft/proprietary/bin/dumptool:system/bin/dumptool \
vendor/huawei/hi6210sft/proprietary/bin/eventcat:system/bin/eventcat \
vendor/huawei/hi6210sft/proprietary/bin/exfatfsck:system/bin/exfatfsck \
vendor/huawei/hi6210sft/proprietary/bin/filebackup:system/bin/filebackup \
vendor/huawei/hi6210sft/proprietary/bin/firmware_bfg_loglevel:system/bin/firmware_bfg_loglevel \
vendor/huawei/hi6210sft/proprietary/bin/get_board_ver:system/bin/get_board_ver \
vendor/huawei/hi6210sft/proprietary/bin/get_chip_ver:system/bin/get_chip_ver \
vendor/huawei/hi6210sft/proprietary/bin/get_param_ver:system/bin/get_param_ver \
vendor/huawei/hi6210sft/proprietary/bin/gnss_engine:system/bin/gnss_engine \
vendor/huawei/hi6210sft/proprietary/bin/hi110x_dump:system/bin/hi110x_dump \
vendor/huawei/hi6210sft/proprietary/bin/hi110x_except_logd:system/bin/hi110x_except_logd \
vendor/huawei/hi6210sft/proprietary/bin/hi110x_logd:system/bin/hi110x_logd \
vendor/huawei/hi6210sft/proprietary/bin/hisi_connectivity.sh:system/bin/hisi_connectivity.sh \
vendor/huawei/hi6210sft/proprietary/bin/hostapd:system/bin/hostapd \
vendor/huawei/hi6210sft/proprietary/bin/hostapd_cli_hisi:system/bin/hostapd_cli_hisi \
vendor/huawei/hi6210sft/proprietary/bin/hostapd_hisi:system/bin/hostapd_hisi \
vendor/huawei/hi6210sft/proprietary/bin/huawei_tp_test:system/bin/huawei_tp_test \
vendor/huawei/hi6210sft/proprietary/bin/libcgroup.so:system/bin/libcgroup.so \
vendor/huawei/hi6210sft/proprietary/bin/mkexfatfs:system/bin/mkexfatfs \
vendor/huawei/hi6210sft/proprietary/bin/mkntfs:system/bin/mkntfs \
vendor/huawei/hi6210sft/proprietary/bin/modem_resetinfo:system/bin/modem_resetinfo \
vendor/huawei/hi6210sft/proprietary/bin/modemlogcat_lte:system/bin/modemlogcat_lte \
vendor/huawei/hi6210sft/proprietary/bin/ntfs-3g:system/bin/ntfs-3g \
vendor/huawei/hi6210sft/proprietary/bin/oam_app:system/bin/oam_app \
vendor/huawei/hi6210sft/proprietary/bin/octty:system/bin/octty \
vendor/huawei/hi6210sft/proprietary/bin/pcscd:system/bin/pcscd \
vendor/huawei/hi6210sft/proprietary/bin/powerlogd:system/bin/powerlogd \
vendor/huawei/hi6210sft/proprietary/bin/preparesd.sh:system/bin/preparesd.sh \
vendor/huawei/hi6210sft/proprietary/bin/server_agent:system/bin/server_agent \
vendor/huawei/hi6210sft/proprietary/bin/set_log:system/bin/set_log \
vendor/huawei/hi6210sft/proprietary/bin/shutdownanimation:system/bin/shutdownanimation \
vendor/huawei/hi6210sft/proprietary/bin/sleeplogcat:system/bin/sleeplogcat \
vendor/huawei/hi6210sft/proprietary/bin/start_110x_service.sh:system/bin/start_110x_service.sh \
vendor/huawei/hi6210sft/proprietary/bin/supl20clientd:system/bin/supl20clientd \
vendor/huawei/hi6210sft/proprietary/bin/thermal-daemon:system/bin/thermal-daemon \
vendor/huawei/hi6210sft/proprietary/bin/wl:system/bin/wl \
vendor/huawei/hi6210sft/proprietary/bin/wl_config:system/bin/wl_config \
vendor/huawei/hi6210sft/proprietary/bin/wpa_cli_hisi:system/bin/wpa_cli_hisi \
vendor/huawei/hi6210sft/proprietary/bin/wpa_supplicant_hisi:system/bin/wpa_supplicant_hisi \
vendor/huawei/hi6210sft/proprietary/lib/cp_if.so:system/lib/cp_if.so \
vendor/huawei/hi6210sft/proprietary/lib/imedia_filters.so:system/lib/imedia_filters.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_atprotocolsw.so:system/lib/lib_atprotocolsw.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_hwnsd_input.so:system/lib/lib_hwnsd_input.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_ffmpeg.so:system/lib/lib_k3_ffmpeg.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omx_avc.so:system/lib/lib_k3_omx_avc.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omx_avcenc.so:system/lib/lib_k3_omx_avcenc.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omx_mpeg2.so:system/lib/lib_k3_omx_mpeg2.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omx_mpeg4.so:system/lib/lib_k3_omx_mpeg4.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omx_rv.so:system/lib/lib_k3_omx_rv.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omx_vc1.so:system/lib/lib_k3_omx_vc1.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omx_vp8.so:system/lib/lib_k3_omx_vp8.so \
vendor/huawei/hi6210sft/proprietary/lib/lib_k3_omxcore.so:system/lib/lib_k3_omxcore.so \
vendor/huawei/hi6210sft/proprietary/lib/libadc_old_sdk.so:system/lib/libadc_old_sdk.so \
vendor/huawei/hi6210sft/proprietary/lib/libaes.so:system/lib/libaes.so \
vendor/huawei/hi6210sft/proprietary/lib/libagnssal.so:system/lib/libagnssal.so \
vendor/huawei/hi6210sft/proprietary/lib/libairsharing_platform.so:system/lib/libairsharing_platform.so \
vendor/huawei/hi6210sft/proprietary/lib/libatpswdck.so:system/lib/libatpswdck.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudioalgoservice_jni.so:system/lib/libaudioalgoservice_jni.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudioresampler.so:system/lib/libaudioresampler.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudio_custom.so:system/lib/libaudio_custom.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudio_custom.so:system/lib/libaudio_custom.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudiopolicymanager.so:system/lib/libaudiopolicymanager.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudiopolicymanagerdefault.so:system/lib/libaudiopolicymanagerdefault.so \
vendor/huawei/hi6210sft/proprietary/lib/libaudioutils.so:system/lib/libaudioutils.so \
vendor/huawei/hi6210sft/proprietary/lib/libavcodec.so:system/lib/libavcodec.so \
vendor/huawei/hi6210sft/proprietary/lib/libavformat.so:system/lib/libavformat.so \
vendor/huawei/hi6210sft/proprietary/lib/libavutil.so:system/lib/libavutil.so \
vendor/huawei/hi6210sft/proprietary/lib/libbalong-ril.so:system/lib/libbalong-ril.so \
vendor/huawei/hi6210sft/proprietary/lib/libbalong-ril-1.so:system/lib/libbalong-ril-1.so \
vendor/huawei/hi6210sft/proprietary/lib/libBestShot.so:system/lib/libBestShot.so \
vendor/huawei/hi6210sft/proprietary/lib/libbluetoothex_jni.so:system/lib/libbluetoothex_jni.so \
vendor/huawei/hi6210sft/proprietary/lib/libbluetooth_jni.so:system/lib/libbluetooth_jni.so \
vendor/huawei/hi6210sft/proprietary/lib/libbreakpad.so:system/lib/libbreakpad.so \
vendor/huawei/hi6210sft/proprietary/lib/libbspatchhwouc.so:system/lib/libbspatchhwouc.so \
vendor/huawei/hi6210sft/proprietary/lib/libbt_factory_test.so:system/lib/libbt_factory_test.so \
vendor/huawei/hi6210sft/proprietary/lib/libbt_factory_test_hi110x.so:system/lib/libbt_factory_test_hi110x.so \
vendor/huawei/hi6210sft/proprietary/lib/libcamera_omron.so:system/lib/libcamera_omron.so \
vendor/huawei/hi6210sft/proprietary/lib/libcamera_post_mediaserver.so:system/lib/libcamera_post_mediaserver.so \
vendor/huawei/hi6210sft/proprietary/lib/libcares.so:system/lib/libcares.so \
vendor/huawei/hi6210sft/proprietary/lib/libcgroup.so:system/lib/libcgroup.so \
vendor/huawei/hi6210sft/proprietary/lib/libchrlog.so:system/lib/libchrlog.so \
vendor/huawei/hi6210sft/proprietary/lib/libcontactsmatchname.so:system/lib/libcontactsmatchname.so \
vendor/huawei/hi6210sft/proprietary/lib/libevent.so:system/lib/libevent.so \
vendor/huawei/hi6210sft/proprietary/lib/libfb.so:system/lib/libfb.so \
vendor/huawei/hi6210sft/proprietary/lib/libfb_cpucapabilities.so:system/lib/libfb_cpucapabilities.so \
vendor/huawei/hi6210sft/proprietary/lib/libfb_creativeediting.so:system/lib/libfb_creativeediting.so \
vendor/huawei/hi6210sft/proprietary/lib/libfb_crypto.so:system/lib/libfb_crypto.so \
vendor/huawei/hi6210sft/proprietary/lib/libfb_dalvik-internals.so:system/lib/libfb_dalvik-internals.so \
vendor/huawei/hi6210sft/proprietary/lib/libfb_ffmpeg.so:system/lib/libfb_ffmpeg.so \
vendor/huawei/hi6210sft/proprietary/lib/libfb_ffmpeg_jni.so:system/lib/libfb_ffmpeg_jni.so \
vendor/huawei/hi6210sft/proprietary/lib/libfm_interface.so:system/lib/libfm_interface.so \
vendor/huawei/hi6210sft/proprietary/lib/libfm_jni.so:system/lib/libfm_jni.so \
vendor/huawei/hi6210sft/proprietary/lib/libfm_volume.so:system/lib/libfm_volume.so \
vendor/huawei/hi6210sft/proprietary/lib/libgnssadapter.so:system/lib/libgnssadapter.so \
vendor/huawei/hi6210sft/proprietary/lib/libhardware_legacy_bcm.so:system/lib/libhardware_legacy_bcm.so \
vendor/huawei/hi6210sft/proprietary/lib/libhardware_legacy_hisi.so:system/lib/libhardware_legacy_hisi.so \
vendor/huawei/hi6210sft/proprietary/lib/libhelixplayer.so:system/lib/libhelixplayer.so \
vendor/huawei/hi6210sft/proprietary/lib/libhisi_efuse.so:system/lib/libhisi_efuse.so \
vendor/huawei/hi6210sft/proprietary/lib/libhisi_ini.so:system/lib/libhisi_ini.so \
vendor/huawei/hi6210sft/proprietary/lib/libhuaweiaudioeffectutil.so:system/lib/libhuaweiaudioeffectutil.so \
vendor/huawei/hi6210sft/proprietary/lib/libhwdeviceinfo.so:system/lib/libhwdeviceinfo.so \
vendor/huawei/hi6210sft/proprietary/lib/libhwextdevice.so:system/lib/libhwextdevice.so \
vendor/huawei/hi6210sft/proprietary/lib/libjpegenchw.so:system/lib/libjpegenchw.so \
vendor/huawei/hi6210sft/proprietary/lib/libmax98925.so:system/lib/libmax98925.so \
vendor/huawei/hi6210sft/proprietary/lib/libmedia.so:system/lib/libmedia.so \
vendor/huawei/hi6210sft/proprietary/lib/libmedia_jni.huawei.so:system/lib/libmedia_jni.huawei.so \
vendor/huawei/hi6210sft/proprietary/lib/libmediarecorder.huawei.so:system/lib/libmediarecorder.huawei.so \
vendor/huawei/hi6210sft/proprietary/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
vendor/huawei/hi6210sft/proprietary/lib/libnfc_nci_jni.so:system/lib/libnfc_nci_jni.so \
vendor/huawei/hi6210sft/proprietary/lib/libnfc-nci.so:system/lib/libnfc-nci.so \
vendor/huawei/hi6210sft/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
vendor/huawei/hi6210sft/proprietary/lib/libpowergenie_native3.so:system/lib/libpowergenie_native3.so \
vendor/huawei/hi6210sft/proprietary/lib/libsensorsgps.so:system/lib/libsensorsgps.so \
vendor/huawei/hi6210sft/proprietary/lib/libsqlite3.so:system/lib/libsqlite3.so \
vendor/huawei/hi6210sft/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
vendor/huawei/hi6210sft/proprietary/lib/libstagefright.huawei.so:system/lib/libstagefright.huawei.so \
vendor/huawei/hi6210sft/proprietary/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
vendor/huawei/hi6210sft/proprietary/lib/libstagefright_soft_ffmpegaudiodec.so:system/lib/libstagefright_soft_ffmpegaudiodec.so \
vendor/huawei/hi6210sft/proprietary/lib/libstagefright_soft_ffmpegvideodec.so:system/lib/libstagefright_soft_ffmpegvideodec.so \
vendor/huawei/hi6210sft/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl10client.so:system/lib/libsupl10client.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20client.so:system/lib/libsupl20client.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20comon.so:system/lib/libsupl20comon.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20if.so:system/lib/libsupl20if.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20oasn1comn.so:system/lib/libsupl20oasn1comn.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20oasn1lpp.so:system/lib/libsupl20oasn1lpp.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20oasn1rrc.so:system/lib/libsupl20oasn1rrc.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20oasn1rrlp.so:system/lib/libsupl20oasn1rrlp.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20oasn1supl1.so:system/lib/libsupl20oasn1supl1.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20oasn1supl2.so:system/lib/libsupl20oasn1supl2.so \
vendor/huawei/hi6210sft/proprietary/lib/libsupl20oasn1tia.so:system/lib/libsupl20oasn1tia.so \
vendor/huawei/hi6210sft/proprietary/lib/libtfa9895.so:system/lib/libtfa9895.so \
vendor/huawei/hi6210sft/proprietary/lib/libwifipro.so:system/lib/libwifipro.so \
vendor/huawei/hi6210sft/proprietary/lib/libwpa_client_hisi.so:system/lib/libwpa_client_hisi.so \
vendor/huawei/hi6210sft/proprietary/lib64/lib_hwnsd_input.so:system/lib64/lib_hwnsd_input.so \
vendor/huawei/hi6210sft/proprietary/lib64/libaes.so:system/lib64/libaes.so \
vendor/huawei/hi6210sft/proprietary/lib64/libagnssal.so:system/lib64/libagnssal.so \
vendor/huawei/hi6210sft/proprietary/lib64/libaudio_custom.so:system/lib64/libaudio_custom.so \
vendor/huawei/hi6210sft/proprietary/lib64/libaudioalgoservice_jni.so:system/lib64/libaudioalgoservice_jni.so \
vendor/huawei/hi6210sft/proprietary/lib64/libaudio-resampler.so:system/lib64/libaudio-resampler.so \
vendor/huawei/hi6210sft/proprietary/lib64/libaudioroute.so:system/lib64/libaudioroute.so \
vendor/huawei/hi6210sft/proprietary/lib64/libbastet.so:system/lib64/libbastet.so \
vendor/huawei/hi6210sft/proprietary/lib64/libbluetoothex_jni.so:system/lib64/libbluetoothex_jni.so \
vendor/huawei/hi6210sft/proprietary/lib64/libchrlog.so:system/lib64/libchrlog.so \
vendor/huawei/hi6210sft/proprietary/lib64/libgnssadapter.so:system/lib64/libgnssadapter.so \
vendor/huawei/hi6210sft/proprietary/lib64/libhisi_efuse.so:system/lib64/libhisi_efuse.so \
vendor/huawei/hi6210sft/proprietary/lib64/libhisi_ini.so:system/lib64/libhisi_ini.so \
vendor/huawei/hi6210sft/proprietary/lib64/libmax98925.so:system/lib64/libmax98925.so \
vendor/huawei/hi6210sft/proprietary/lib64/libmediarecorder.huawei.so:system/lib64/libmediarecorder.huawei.so \
vendor/huawei/hi6210sft/proprietary/lib64/liboeminfo.so:system/lib64/liboeminfo.so \
vendor/huawei/hi6210sft/proprietary/lib64/libpowergenie_native3.so:system/lib64/libpowergenie_native3.so \
vendor/huawei/hi6210sft/proprietary/lib64/libstagefright.huawei.so:system/lib64/libstagefright.huawei.so \
vendor/huawei/hi6210sft/proprietary/lib64/libstagefright_soft_ffmpegaudiodec.so:system/lib64/libstagefright_soft_ffmpegaudiodec.so \
vendor/huawei/hi6210sft/proprietary/lib64/libstagefright_soft_ffmpegvideodec.so:system/lib64/libstagefright_soft_ffmpegvideodec.so \
vendor/huawei/hi6210sft/proprietary/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
vendor/huawei/hi6210sft/proprietary/lib64/libtfa9895.so:system/lib64/libtfa9895.so \
vendor/huawei/hi6210sft/proprietary/lib64/libwifipro.so:system/lib64/libwifipro.so 